// Build information, automatically generated by `ng-info`
const build = {
    version: "0.0.24",
    timestamp: "Wed Jan 17 2024 19:11:41 GMT+0530 (India Standard Time)",
    message: null,
    git: {
        user: "i727097",
        branch: "B-175017",
        hash: "043805",
        fullHash: "04380566f0e7627ab41b3bc4c2df035302959ee2"
    }
};

export default build;