export const environment = {
  production: false,
  livereload: false,
  baseUrl: 'https://myvoyage.accp.app.voya.com/',
  tpaPrefix: 'ACCP-',
  tpaSdk: '1a1d68b8-93c1-41ac-bced-16d1624c527f',
  tokenBaseUrl: 'https://token.accp.app.voya.com/',
  myvoyaBaseUrl: 'https://myvoya.accp.app.voya.com/',
  loginBaseUrl: 'https://login.accp.voya.com/',
  savviBaseUrl: 'https://myhealthwealth.accp.voya.com/',
  authClientID: 'myvoyage_app_SMhdbA0WYdvNnZrxoGoj',
  authTokenExchangeClient: 'myvoyage_app_token_exchange_HRLyAVubwplCeJustemv',
  ssoSamlUrl: 'https://sso.test.myvoya.com',
  openIdConfigurationUrl: 'oidcop/app/.well-known/openid-configuration',
  samlAudience: 'saml/sps/saml-idp-login/saml20',
};
