export const environment = {
  production: false,
  livereload: false,
  baseUrl: 'https://myvoyage2.intg.app.voya.com/',
  tpaPrefix: 'INTG-',
  tpaSdk: '1a1d68b8-93c1-41ac-bced-16d1624c527f',
  tokenBaseUrl: 'https://token.intg.app.voya.com/',
  myvoyaBaseUrl: 'https://myvoya-my4.intg.app.voya.com/',
  loginBaseUrl: 'https://login4.intg.voya.com/',
  savviBaseUrl: 'https://myhealthwealth.intg.voya.com/',
  authClientID: 'myvoyage2_app_vg7moMsaCrqb5U5atkOX',
  authTokenExchangeClient: 'myvoyage_app_token_exchange_8ah5YTB3MIavGzS3UXjj',
  ssoSamlUrl: 'https://sso.myvoya.com',
  openIdConfigurationUrl: 'oidcop/customer4/.well-known/openid-configuration',
  samlAudience: 'saml/sps/saml-idp-login4/saml20',
};
