export const environment = {
  production: true,
  livereload: false,
  tpaPrefix: '',
  tpaSdk: '1286e91c-510c-4481-9c9c-32701d4ce715',
  baseUrl: 'https://myvoyage.app.voya.com/',
  tokenBaseUrl: 'https://token.app.voya.com/',
  myvoyaBaseUrl: 'https://myvoya.app.voya.com/',
  loginBaseUrl: 'https://login.voya.com/',
  savviBaseUrl: 'https://myhealthwealth.voya.com/',
  authClientID: 'myvoyage_app_fVvCZXhgIwpEcx3TLhf5',
  authTokenExchangeClient: 'myvoyage_app_token_exchange_r1JDA30lVcpitjvwkQbt',
  ssoSamlUrl: 'https://sso.myvoya.com',
  openIdConfigurationUrl: 'oidcop/app/.well-known/openid-configuration',
  samlAudience: 'saml/sps/saml-idp-login/saml20',
};
