export const environment = {
  production: false,
  livereload: false,
  baseUrl: 'https://myvoyage3.accp.app.voya.com/',
  tpaPrefix: 'ACCP-',
  tpaSdk: '1a1d68b8-93c1-41ac-bced-16d1624c527f',
  tokenBaseUrl: 'https://token.accp.app.voya.com/',
  myvoyaBaseUrl: 'https://myvoya-my5.accp.app.voya.com/',
  loginBaseUrl: 'https://login5.accp.voya.com/',
  savviBaseUrl: 'https://myhealthwealth.accp.voya.com/',
  authClientID: 'myvoyage3_app_YrvghzpV2ZdLCM5PrIC2',
  authTokenExchangeClient: 'myvoyage_app_token_exchange_HRLyAVubwplCeJustemv',
  ssoSamlUrl: 'https://sso.test.myvoya.com',
  openIdConfigurationUrl: 'oidcop/customer5/.well-known/openid-configuration',
  samlAudience: 'saml/sps/saml-idp-login5/saml20',
};
